#pragma once

#define VIAL_KEYBOARD_UID {0xFA, 0x99, 0xF4, 0x92, 0x56, 0x9E, 0x36, 0xD1}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 3, 5 }

#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_INVERT
